# Generated by Django 3.2.6 on 2021-09-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='admission_no',
            field=models.CharField(default='IS/57/15', max_length=20),
        ),
        migrations.AddField(
            model_name='apply',
            name='email_address',
            field=models.EmailField(default='toriong@gmail.com', max_length=254),
        ),
    ]
